### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/native-chart-experiment#1]
- [x] Pass data from react native (properties)
- [x] Adjust colour (for dark mode)
- [x] Option to draw a line
- [x] Support Line Chart
- [x] Support Horizontal Line Chart
- [x] Support Pie Chart
- [x] Support Bar Chart
- [x] Support Android
   - [x] convert swift to kotlin
- [x] Code cleanup??

Maybe more charts if I use them.

**Comment by HenryQuan** [comment]
This project won't have new features anymore.
